# Generated by Django 3.1.2 on 2021-01-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bestseller',
            fields=[
                ('sr', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.IntegerField(unique=True)),
                ('title', models.CharField(default='', max_length=500)),
                ('author', models.CharField(default='', max_length=5000)),
                ('thumnail', models.ImageField(upload_to='bestseller')),
                ('content', models.TextField(blank=True)),
                ('publish_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
