# Generated by Django 3.1.4 on 2021-01-03 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bestseller', '0003_auto_20210103_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bestseller',
            name='publish_date',
        ),
    ]
