# Generated by Django 3.1.4 on 2021-01-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bestseller', '0004_remove_bestseller_publish_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bestseller',
            name='is_publish',
        ),
        migrations.AddField(
            model_name='bestseller',
            name='publish_date',
            field=models.DateField(null=True),
        ),
    ]
