# Generated by Django 3.1.4 on 2021-01-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Art', '0002_remove_art_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='publish_date',
            field=models.DateField(null=True),
        ),
    ]
