# Generated by Django 3.1.4 on 2021-01-03 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='publish_date',
        ),
    ]
