# Generated by Django 3.1.4 on 2021-01-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Education', '0002_remove_education_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='publish_date',
            field=models.DateField(null=True),
        ),
    ]
