# Generated by Django 3.1.4 on 2021-01-03 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fantacy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fantacy',
            name='publish_date',
        ),
    ]
