# Generated by Django 3.1.4 on 2021-01-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fantacy', '0002_remove_fantacy_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantacy',
            name='publish_date',
            field=models.DateField(null=True),
        ),
    ]
